name: general

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
  pull_request:
    branches:
      - master

jobs:

  # Test

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: Install dependencies
        run: npm install
      - name: Test software
        run: npm test
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: opendatacensus_test
          # POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

  # Deploy

  # deploy:
    # if: github.event_name == 'push'
    # runs-on: ubuntu-latest
    # steps:
      # - name: Checkout repository
        # uses: actions/checkout@v2
      # - name: Install Node
        # uses: actions/setup-node@v1
        # with:
          # node-version: 14
      # - name: Install and build site
        # run: |
          # cd site
          # npm install
          # npm run build
      # - name: Publush to Github Pages
        # uses: JamesIves/github-pages-deploy-action@3.7.1
        # with:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # BRANCH: site
          # FOLDER: site/build
          # CLEAN: true
